### ISSUE TITLE
Add some additional arguments

### ISSUE THREAD

**Issue by leeper** [zmeers/ggparliament#1]
- [x] make labels optional: party name, number of seats, both, or neither
- [ ] other styles:
  - [x] `"bar"`
  - [ ] `"pie"`
  - [x] `"rose"`
  - [ ] `"waffle"`
  - [ ] "u" - for Australian-style U-shaped parliament
- [ ] allow arbitrary number of rings in arc-style?
- [ ] seat total as a huge number in the center like in similar packages
- [ ] line showing majority threshold

**Comment by RobWHickman** [comment]
managed to add some of these (e.g. the line showing majority, correct party ordering, colours etc. at https://github.com/RobWHickman/ggparliament. needs a lot of tidying before a proper pull request. Is there anything it desperately needs? I think arbitrary ring number (and multiple rings in general for dots) is the big one?

**Comment by leeper** [comment]
Cool! Yea, both of those would probably be good.

**Comment by zmeers** [comment]
I've been playing around with ggforce::geom_arc_bar() and it's fairly easy to create U-shaped parliament for Australia and NZ. I'll add a PR once we've transferred the repo over to Rob. I'm also working on a waffle-style Westminster parliament.

**Comment by zmeers** [comment]
I would also like to add the ability to highlight reserved seats and coalitions.
