### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by zmeers** [zmeers/ggparliament#13]
Just chatted with my advisor and I spoke with Thomas ~1 month ago about writing an academic paper for `ggparliament`.  
Places we can think about submitting to:
- _Legislative Studies Quarterly_ (Research note?)
- _Electoral Studies_ (Research note?)
- _Journal of Statistical Software_ (Long wait time...~2 years.)
- _Journal of Open Source Software_ (Quick turnaround, short pieces, not polisci-oriented.)
- _The Political Methodologist_ (This is really a newsletter for polmeth and isn't peer reviewed so it's more of a last resort IMO.)

I'm happy to do most (all?) of the legwork for this if you're not interested, @RobWHickman. Just throwing the idea out there. I'm not sure if you're interested in doing more academic work.

**Comment by RobWHickman** [comment]
tbh I'm going to be swamped with grad school stuff mostly. Happy to help out wherever I can but more than happy for you to take the lead on this. Seems like you'd know a lot more about the field(s) anyway!

I'd rather keep it polsci orientated as it's a bug bear of mine in biology that useful bio packages don't get published as 'biology' quite a lot. But again, you know a lot more than me here
