### ISSUE TITLE
Unknown or uninitialised column: 'party'. 

### ISSUE THREAD

**Issue by RobWHickman** [zmeers/ggparliament#19]
parliament_data giving this error. Everything seems to be working so I assume its a case of just going through the code and removing this. Will leave it for the immediate future as it isn't breaking anything

**Comment by zmeers** [comment]
It looks like we don't even need the party variable. Party_short and party_long expand when the aggregated party seats are unravelled to their length when we use tidyr::uncount(). 
Moreover, it also looks like we don't need party_names in parliament_data, either. We might as well shorten the function where possible, IMO.
