### ISSUE TITLE
error with german government data

### ISSUE THREAD

**Issue by RobWHickman** [zmeers/ggparliament#34]
wayyyy back when we started this I don't think there was actually a coalition in Germany so I can't remember why I went with what I did.

Anyway, for the 2017 election it should be the CDU and the SDP in government

**Comment by zmeers** [comment]
I also think CSU and CDU should be merged into one party because at the federal level they are the same party.

**Comment by zmeers** [comment]
In addition to changing the German data, the Australian Labor Party does not have a 'u' in the name (although we spell labour - as in work - with a 'u').

**Comment by zmeers** [comment]
All issues fixed.
