### ISSUE TITLE
Solid filling

### ISSUE THREAD

**Issue by Aimonius** [zmeers/ggparliament#39]
It's possible to make solid filling instead of points? How?  Thanks a lot for this library!

**Comment by zmeers** [comment]
Hi Jesus,

I'm just wondering if you can clarify what you mean by solid filling? Do you want to change the shape of the point? You can do that by adding the shape argument to `geom_parliament_seats()`. By default, the points are fully opaque (i.e. alpha == 1). If you clarify what you mean by solid filling, we'll be able to help you better. 

Thanks,

Zoe

**Comment by Aimonius** [comment]
Apologies for not having been clear, I was referring to not using points, only a solid filler for each group, like in this example

![resultados7](https://user-images.githubusercontent.com/19475313/52942542-78a35c80-336b-11e9-9091-d470ab1056de.jpg)

**Comment by zmeers** [comment]
I'll tag @RobWHickman on this -- I think he might have done something similar to this in the legacy code...

**Comment by zmeers** [comment]
Will close, it seems like you found what you needed in `ggpol`.
