### ISSUE TITLE
Add JOSS Badge to README

### ISSUE THREAD

**Issue by mpadge** [zmeers/ggparliament#46]
Just noticed you don't have the JOSS badge on your README - it would be helpful if you could add the badge to link directly to the corresponding article:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01313/status.svg)](https://doi.org/10.21105/joss.01313)

**Comment by zmeers** [comment]
Sorry for delayed reply - this has been addressed. Thanks.
