### ISSUE TITLE
Cleaning data

### ISSUE THREAD

**Issue by RobWHickman** [zmeers/ggparliament#6]
The .rda data in /data is a bit unclean- especially ward_results. 

Here's a list of things to do (non-exhaustive)

- Clean up ward_results so all columns are consistent
- Clean up ward_results so passes travis build
- Check colours for the German results
- Generally make sure results are accurate
- Add in 2018 data for ward_results

**Comment by zmeers** [comment]
I'm thinking we might want to add Australian data for u-shaped parliaments. Results for all Australian federal elections can be found in pscl... A few other elections are in pscl as well - I know for sure there are results for some UK and US elections.

**Comment by RobWHickman** [comment]
yeah UK data (for the bench layout) and the Australian data would be good. I'll probs throw some basic datasets together from wikipedia or http://www.globalelectionsdatabase.com/index.php/index- whichever is quicker :)

**Comment by RobWHickman** [comment]
ok I've repackaged the data into a single file (election_data) which contains at least 3 examples for various 'shapes' of parliamentary houses

- UK (commons only atm, can't find good lords data): bench
- Russia: classroom
- Australia (representatives and senate [though cant find reliable senate 2013 data that separates out the coalition- might be worth checking the numbers]): horseshoe
- US (only 3x senate and representatives- we have the data for all the senates/representatives through history which I might add back in for testing purposes [e.g. checking that plots make sense for small and large houses]): semi circle

- Ive kept the german data as I think it's fairly useful for mapping coalitions
- couldn't find a modern example of a complete circular house. Any ideas?

it's all on the election_data branch

once I re-add the american history and either West Germany or something else for the circles I'll pull it across (and close the issue) so we have a common dataset that should account for most things we'd want to do. I reckon for submission we'd want to trim back later for CRAN (to 3x elections for each house type)

**Comment by zmeers** [comment]
North-Rhine Westphalia is a current example of a circular parliament... Unfortunately, it's not a federal example. There is a book on parliament layouts. I can see if it's in my university library tomorrow. The other data sets sound interesting!

**Comment by zmeers** [comment]
Can we close this?
