### ISSUE TITLE
scale_colour_party()

### ISSUE THREAD

**Issue by zmeers** [zmeers/ggparliament#8]
I'll create a PR for `scale_colour_party()` once the repository has been transferred to Rob's account.

**Comment by RobWHickman** [comment]
should be ready now 👍

**Comment by zmeers** [comment]
Hmm. I can't put in a PR until I've been given access to edit the repo ... When you've done that, I'll create a separate branch for my stuff as it's still a bit messy.

**Comment by zmeers** [comment]
The data from the global elections database provides party colours so it's fairly easy for the user to write scale_colour_manual(values=c(country$colour), labels=c(country$party_long)). I'm not sure creating our own scale is worth the hassle, as our colours may not be 100% correct and (re)ordering factors, colours, and labels is painful. Therefore, this issue is tentatively closed. I might come back to this later but it's not a priority.
